on:
  push:
    branches:
    - master
  pull_request:

name: GitBook

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: gitbook-build
        uses: docker://khs1994/gitbook
      - name: gitbook-deploy
        if: github.event_name == 'push'
        uses: docker://khs1994/gitbook
        with:
          args: deploy
        env:
          GIT_USERNAME: "khs1994"
          GIT_USEREMAIL: "khs1994@khs1994.com"
          GIT_BRANCH: "gh-pages"
          # 必须使用自己的 token, actions 的 token 不会触发 master 的 actions
          GITHUB_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
